server {
    listen 80;
    server_name localhost;

    # Serve static React build files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to the FastAPI backend container
    location /api {
        resolver [fd12::10] ipv6=on valid=1s;
        set $backend_service http://medicalchatbot.railway.internal:10000;
        proxy_pass $backend_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
