services:
  backend:
    build: ./backend
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - ./backend/medical.db:/app/medical.db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
